name: Deploy to EC2

on:
  push:
    branches:
      - main 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.2
      with:
        key: ${{ secrets.EC2_KEY }}
        username: ${{ secrets.EC2_USER }}
        host: ${{ secrets.EC2_HOST }}
        port: 22
        script: |
         export NVM_DIR="$HOME/.nvm"
         [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
         nvm use 22.16.0
         cd /home/ubuntu/fatepet-fe
         git fetch origin
         git checkout main
         git pull origin main
         npm install
         npm run build
         pm2 restart next-app